[tool.poetry]
name = "proyecto-grado"
version = "0.1.0"
description = ""
authors = ["Facundo Spira <facundospira@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
PuLP = "^2.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
